### ISSUE TITLE
A transition API for DOM elements

### ISSUE THREAD

**Issue by robinvdvleuten** [phoenixframework/phoenix_live_view#812]
It would be very nice to have some sort of transition API in a similar fashion as React, Vue, Angular, etc. A small example could look like this;

```html
<div phx-transition="fade"></div>
```

```css
.fade-enter-active, .fade-leave-active {
  transition: opacity .2s;
}

.fade-enter, .fade-leave {
  opacity: 0;
}
```

As Livewire uses `morphdom` as well, I dug up the code responsible for their transitions (https://github.com/livewire/livewire/commit/5707bd6d39f2d61f79906ab07371d669aafb2fb1). If you look closely, I think only two methods needs to be added (`transitionElementIn` and `transitionElementOut`).

Otherwise, if this feels as too much functionality to add, maybe Liveview can allow hooks to delay enter and delete calls by returning something like a promise so the user can do the transitioning by themself?

I can make a PR with a POC for this if there is enough enthusiasm.
